# Generated by Django 2.2.5 on 2022-06-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220604_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='issue',
        ),
        migrations.AddField(
            model_name='task',
            name='recomendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='treatement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
